### ISSUE TITLE
Radiosonde data sources

### ISSUE THREAD

**Issue by ramespada** [projecthorus/sondehub-infra#108]
Hi!

Sorry this is not an issue but a question about if there is a centralized database of global radiosonde data (not possition only but the data itself: temp, humidity, pressure, height, wind dir and speed, etc.). I usually use [The Integrated Global Radiosonde Archive (IGRA)](https://www.ncei.noaa.gov/products/weather-balloon/integrated-global-radiosonde-archive) and [NOAA/ESRL Radiosonde Database]( https://ruc.noaa.gov/raobs/) but they doesn't have some radiosondes that your app does have, and I wonder if the data is somewhere else. Also ask if you know the exactly "raw data format" that comes from this sensors (cause I may need to create a parser for my personal application). 

Lastly thanks for all your work, is truly great!

Regards!

**Comment by darksidelemm** [comment]
I'm not sure there's any one database that covers everything. Not all nations participate in all of the organisations that collate this data.

If by 'raw data' you mean what comes off the radiosonde, then this varies a lot between radiosonde types, and there's also work that has to be done to convert the raw data into real values using calibration parameters (which we don't do 'correctly' for all radiosonde types due to the difficulty).

This repository provides some information on various radiosonde types: https://github.com/bazjo/radiosonde_hardware

**Comment by TheSkorm** [comment]
I'm going to close this ticket for now, plus please comment on here if you need any more info.
