### ISSUE TITLE
Nice to have: horizontal speed plot in Grafana

### ISSUE THREAD

**Issue by zanco** [projecthorus/sondehub-infra#111]
During a summerstorm PD3EGE launched an 4fsk tracker. It would be really nice to re-view the horizontal speed in Grafana too.

https://grafana.v2.sondehub.org/d/HJgOZLq7k/basic?var-Payload=PD3EGE&from=1688545183000&to=now&orgId=1&refresh=1m

Thanks,

**Comment by TheSkorm** [comment]
This is one of those things that sounds really simple to do but is actually quite hard in Grafana. I actually spent most of tonight looking at different approaches to doing this and I couldn't find anything suitable yet. 

The two closest solutions I have is:
 - developing an API that queries sondehub db and calculates the horizontal speed that can then be loaded into grafana
 - using something like echarts https://volkovlabs.io/plugins/volkovlabs-echarts-panel/options/ to create a custom chart / data processing for it

I'm leaning towards the echarts approach as it may be useful for other charts that require complex processing.

For now the only work around I can offer is download the data in json format and using some other tool to calculate it.

**Comment by darksidelemm** [comment]
As a way to get a little bit closer to this, at least for some payloads, I've updated Horus-GUI (in v0.3.12), and HorusDemodLib (v0.3.11) to upload the speed information which is present in Horus Binary v2 payload telemetry. Note that the speed indication in Horus v2 is in km/hr, and will wrap at 256 km/hr!

Users will need to update to the latest versions of these apps for this to be uploaded and be available for use on dashboards.
For Horus-GUI, just grab the latest release at https://github.com/projecthorus/horus-gui/releases/tag/v0.3.12

For horusdemodlib, you will need to update the python package with something like:
```
pip3 install -U horusdemodlib
```
Depending on your installation this might need to be run within a virtualenv.

Hopefully we can get echarts going as well, as this will let us do speed and maybe other calculations for payloads that don't report this information in telemetry.

**Comment by zanco** [comment]
It was nice to see that round 08:00 UTC the first stations updated their software :-)

**Comment by TheSkorm** [comment]
I've added an experimental eCharts widget that tries to calculate speed. There's a few issues though however.

- The data seems to end up with spikes in it - not sure why this happens - it seems to be related to intervals and at some zoom levels / intervals it doesn't happen.
- Since it's not a grafana graph the cross hairs don't map across, also the data extents are aligned to what data is available rather that the requests area (this might be easy to fix , I haven't checked)
- The timezone is always going to be based on browser time due to https://github.com/apache/echarts/issues/14453

<img width="798" alt="image" src="https://github.com/projecthorus/sondehub-infra/assets/234867/279b4993-97e9-4fac-810e-26867307c7b9">
<img width="769" alt="image" src="https://github.com/projecthorus/sondehub-infra/assets/234867/937964e0-0b6f-473c-b94a-25613f6612ee">
<img width="794" alt="image" src="https://github.com/projecthorus/sondehub-infra/assets/234867/5db2cd99-07f8-4235-8aa0-d369e3fa7880">

**Comment by TheSkorm** [comment]
<img width="781" alt="image" src="https://github.com/projecthorus/sondehub-infra/assets/234867/c5baa0ae-a657-48b7-8cfd-8bfce9fa4906">
the time range wasn't too hard to fix, though I'm not sure how hacky it is.

**Comment by TheSkorm** [comment]
<img width="758" alt="image" src="https://github.com/projecthorus/sondehub-infra/assets/234867/82b7d0bc-9e13-4dc4-b962-f85febc8148c">
I set the lookback from one day point to 10 to give it more distance and time delta. It's little fuzzy but it's probably "good enough"

<img width="773" alt="image" src="https://github.com/projecthorus/sondehub-infra/assets/234867/b29d6ffe-f899-4fa6-b984-f287d08b7b99">
There was this problem where the speed shot off to a large number. Not entirely sure why given that we filter for sats == 0 

For now I've set it to discard anything greater than 1000.

**Comment by zanco** [comment]
Thanks again, yesterday evening PD3EGE had an 4fsk flight, and this morning he talked to me about the excessive speeds het noted yesterday evening for his payload, and the big bumps ;-) I asked him to show me what he meant and all his problems where allready solved by the developer(s) :-)

![image](https://github.com/projecthorus/sondehub-infra/assets/4477734/a80e50bb-7f40-4fce-b2d7-e493f343f6b4)

**Comment by darksidelemm** [comment]
That's what we get for testing this stuff on a 'production' dashboard :-P

**Comment by TheSkorm** [comment]
Only thing that still needs to be fixed is the timezone issue, however this is waiting for upstream fix. Closing for now.
