### ISSUE TITLE
Amateur balloon predictions

### ISSUE THREAD

**Issue by TheSkorm** [projecthorus/sondehub-infra#64]

**Comment by darksidelemm** [comment]
For amateur flight predictions I would suggest using the following as the 'default' parameters:
* Ascent Rate: 5m/s
* Burst Altitude: 30000m
* Descent Rate: 5m/s

... however, these will not always suffice. We need an API where a user can submit 'real' parameters for a particular callsign. I suggest this is tied to a callsign, not a 'flight' (which is something covered in another issue), so that the prediction system can work in a similar away to the current sondehub predictions.

The API should accept the following parameters:
* `payload_callsign` - The payload callsign these prediction parameters apply to. 
* `float_expected` - A true/false flag, which defines if this launch is expected to float. If this is set to true and the payload is on ascent, the Tawhiri 'float_profile' is used when running predictions instead of the regular profile.
* `peak_altitude` - The expected burst, or float altitude, in metres.
* `descent_rate` - The expected sea-level descent rate of the payload, in m/s.
* `suggester_callsign` - The 'callsign' or name of the person suggesting the change. Make this a mandatory field.

We may also want to add as an optional field:
* `ascent_rate` - The expected ascent rate of the payload, in m/s.
... however, this would only really be useful when the payload is on-ground before launch. I'm not sure if adding in reliable 'on ground before launch' detection is that simple. I would suggest having it in the API, but we may never use it.

I would suggest that when a new submission is entered, it replaces any old parameters for the particular payload_callsign.

**Comment by TheSkorm** [comment]
This will be covered in #63
